function tf = signatures_equal_exp4(a,b)
%SIGNATURES_EQUAL_EXP4 Strict compatibility check for final Exp4 checkpoints.
    tf=false;
    fields={'version','medium','modelType','materialParameters','gpuProduction','N', ...
        'pathSubintervals','nev','p','tolLanczos','tolCG','pointIndex','q','selectedMode'};
    for j=1:numel(fields)
        if ~isfield(a,fields{j}) || ~isfield(b,fields{j}), return; end
    end

    if ~isfield(a,'numerics') || ~isfield(b,'numerics') || ...
            ~isequaln(a.numerics,b.numerics) || ...
            numel(a.materialParameters)~=numel(b.materialParameters), return; end
    tf = isequal(a.version,b.version) && strcmp(a.medium,b.medium) && ...
        strcmp(a.modelType,b.modelType) && a.gpuProduction==b.gpuProduction && ...
        norm(double(a.materialParameters(:))-double(b.materialParameters(:)),inf)<1e-13 && ...
        a.N==b.N && a.pathSubintervals==b.pathSubintervals && ...
        a.nev==b.nev && a.p==b.p && ...
        a.tolLanczos==b.tolLanczos && a.tolCG==b.tolCG && ...
        a.pointIndex==b.pointIndex && ...
        norm(double(a.q(:))-double(b.q(:)),inf)<1e-14 && ...
        double(a.selectedMode)==double(b.selectedMode);
end
