function s = make_BC_fig1a_signature(cfg,method,gpuInfo)
%MAKE_BC_FIG1A_SIGNATURE Checkpoint compatibility signature for B/C Fig.1(a).
    s = struct();
    s.version = 1;
    s.figure = '1a';
    s.method = upper(char(method));
    s.N = cfg.problem.N;
    s.numEig = cfg.spectrum.numEig;
    s.P = cfg.problem.P;
    s.T = cfg.problem.T;
    s.epsC = cfg.material.epsC;
    s.alpha = cfg.material.alpha;
    s.massBackend = cfg.mass.backend;
    s.pathVertices = cfg.path.vertices;
    s.pathInteriorFractions = cfg.path.interiorFractions;
    s.lanczosP = cfg.lanczos.krylovDimension;
    s.lanczosTol = cfg.lanczos.tolerance;
    s.lanczosMaxRestartCycles = cfg.lanczos.maxRestartCycles;
    s.lanczosSeed = cfg.lanczos.rngSeed;
    s.tolKr = cfg.nested.tolKr;
    s.tolM = cfg.nested.tolM;
    s.maxitKr = cfg.nested.maxitKr;
    s.maxitM = cfg.nested.maxitM;
    s.useKrPreconditioner = cfg.nested.useKrPreconditioner;
    s.tolMhat = cfg.explicit.tolMhat;
    s.maxitMhat = cfg.explicit.maxitMhat;
    s.gpuName = gpuInfo.name;
    s.matlabVersion = version;
end
