function one = run_method_B_fig1bc(sys,cfg,seed,budget)
%RUN_METHOD_B_FIG1BC Nested reduced inverse with CPU-outer/GPU-inner Lanczos.

    [Aop,getStats]=make_nested_krinv_instrumented(sys,cfg,cfg.nested.tolKr,cfg.nested.tolM, ...
        cfg.nested.maxitKr,cfg.nested.maxitM,budget);
    rng(seed,'twister');
    v0=randn(sys.nr,1)+1i*randn(sys.nr,1);
    v0=cast(v0,cfg.gpu.precision);
    budget.checkCanContinue('Method B hybrid Lanczos start');
    t=tic;
    [theta,outerSteps,info]=Lanczos_hybrid_identity_gpuop(Aop,sys.nr,cfg.spectrum.numEig, ...
        cfg.lanczos.tolerance,cfg.lanczos.maxRestartCycles,cfg.lanczos.krylovDimension, ...
        v0,cfg.gpu.precision,cfg.lanczos.verboseInternal,budget);
    wall=toc(t); budget.check('Method B hybrid Lanczos return');

    if ~info.converged
        error('EXP1:NotConverged','Method B outer Lanczos did not converge: %d/%d.', ...
            info.numConverged,cfg.spectrum.numEig);
    end
    theta=real(theta(:));
    if any(~isfinite(theta)) || any(theta<=0), error('Method B invalid inverse Ritz values.'); end
    lambda=sort(1./theta,'ascend'); s=getStats();

    one=struct('lambda',lambda,'outerSteps',outerSteps,'inverseCalls',s.inverseCalls, ...
        'totalLinearSolverIterations',s.totalKrIterations+s.totalMassIterations, ...
        'primaryLinearIterations',s.totalKrIterations,'nestedLinearIterations',s.totalMassIterations, ...
        'dominantLinearSolveSeconds',s.totalMassSolveTime, ...
        'remainingInverseSeconds',max(s.totalInverseTime-s.totalMassSolveTime,0), ...
        'outerLanczosSeconds',max(wall-s.totalInverseTime,0),'totalWallSeconds',wall, ...
        'converged',true,'maxFinalRitzResidual',max(info.ritzResiduals{end}), ...
        'maxLinearRelativeResidual',max(s.maxKrRelativeResidual,s.maxMassRelativeResidual), ...
        'averagePrimaryLinearIterations',s.averageKrIterations,'maxPrimaryLinearIterations',s.maxKrIterations, ...
        'averageNestedLinearIterations',s.averageMassIterations,'maxNestedLinearIterations',s.maxMassIterations, ...
        'outerH2DSeconds',info.totalH2DSeconds,'outerD2HSeconds',info.totalD2HSeconds, ...
        'outerGPUOperatorSeconds',info.totalGPUOperatorSeconds,'outerStorage','CPU');
    clear v0
end
