function one = run_method_C_fig1(sys,cfg,seed,budget)
%RUN_METHOD_C_FIG1 Explicit reduced inverse Lanczos.
    [Aop,getStats]=fig1a_make_explicit_krinv_instrumented(sys,cfg.explicit.tolMhat,cfg.explicit.maxitMhat,budget);
    Iop=@(x)x; rng(seed,'twister');
    v0=to_gpu(randn(sys.nr,1)+1i*randn(sys.nr,1),cfg.gpu.precision);
    budget.checkCanContinue('Method C Lanczos start'); wait_for_gpu(v0); t=tic;
    [Y,theta,outerSteps,info]=Lanczos(Aop,Iop,Iop,sys.nr,cfg.spectrum.numEig, ...
        cfg.lanczos.tolerance,cfg.lanczos.maxRestartCycles,cfg.lanczos.krylovDimension, ...
        v0,true,cfg.lanczos.verboseInternal,false,1);
    wait_for_gpu(Y); wall=toc(t); budget.check('Method C Lanczos return');
    if ~info.converged, error('EXP1:NotConverged','Method C outer Lanczos did not converge: %d/%d.',info.numConverged,cfg.spectrum.numEig); end
    theta=real(theta(:)); if any(~isfinite(theta))||any(theta<=0), error('Method C invalid inverse Ritz values.'); end
    lambda=sort(1./theta,'ascend'); s=getStats();
    one=struct('lambda',lambda,'outerSteps',outerSteps,'inverseCalls',s.inverseCalls, ...
        'totalLinearSolverIterations',s.totalMhatIterations,'primaryLinearIterations',s.totalMhatIterations, ...
        'nestedLinearIterations',0,'dominantLinearSolveSeconds',s.totalMhatSolveTime, ...
        'remainingInverseSeconds',max(s.totalInverseTime-s.totalMhatSolveTime,0), ...
        'outerLanczosSeconds',max(wall-s.totalInverseTime,0),'totalWallSeconds',wall, ...
        'converged',true,'maxFinalRitzResidual',gather_scalar(max(info.ritzResiduals{end})), ...
        'maxLinearRelativeResidual',s.maxMhatRelativeResidual, ...
        'averagePrimaryLinearIterations',s.averageMhatIterations,'maxPrimaryLinearIterations',s.maxMhatIterations, ...
        'averageNestedLinearIterations',0,'maxNestedLinearIterations',0);
    clear Y v0
end
