function one = run_method_C_fig1bc(sys,cfg,seed,budget)
%RUN_METHOD_C_FIG1BC Explicit reduced inverse with CPU-outer/GPU-inner Lanczos.

    [Aop,getStats]=make_explicit_krinv_compact(sys,cfg.explicit.tolMhat,cfg.explicit.maxitMhat,budget);
    rng(seed,'twister');
    v0=randn(sys.nr,1)+1i*randn(sys.nr,1);
    v0=cast(v0,cfg.gpu.precision);
    budget.checkCanContinue('Method C hybrid Lanczos start');
    t=tic;
    [theta,outerSteps,info]=Lanczos_hybrid_identity_gpuop(Aop,sys.nr,cfg.spectrum.numEig, ...
        cfg.lanczos.tolerance,cfg.lanczos.maxRestartCycles,cfg.lanczos.krylovDimension, ...
        v0,cfg.gpu.precision,cfg.lanczos.verboseInternal,budget);
    wall=toc(t); budget.check('Method C hybrid Lanczos return');

    if ~info.converged
        error('EXP1:NotConverged','Method C outer Lanczos did not converge: %d/%d.', ...
            info.numConverged,cfg.spectrum.numEig);
    end
    theta=real(theta(:));
    if any(~isfinite(theta)) || any(theta<=0), error('Method C invalid inverse Ritz values.'); end
    lambda=sort(1./theta,'ascend'); s=getStats();

    one=struct('lambda',lambda,'outerSteps',outerSteps,'inverseCalls',s.inverseCalls, ...
        'totalLinearSolverIterations',s.totalMhatIterations, ...
        'primaryLinearIterations',s.totalMhatIterations,'nestedLinearIterations',0, ...
        'dominantLinearSolveSeconds',s.totalMhatSolveTime, ...
        'remainingInverseSeconds',max(s.totalInverseTime-s.totalMhatSolveTime,0), ...
        'outerLanczosSeconds',max(wall-s.totalInverseTime,0),'totalWallSeconds',wall, ...
        'converged',true,'maxFinalRitzResidual',max(info.ritzResiduals{end}), ...
        'maxLinearRelativeResidual',s.maxMhatRelativeResidual, ...
        'averagePrimaryLinearIterations',s.averageMhatIterations,'maxPrimaryLinearIterations',s.maxMhatIterations, ...
        'averageNestedLinearIterations',0,'maxNestedLinearIterations',0, ...
        'outerH2DSeconds',info.totalH2DSeconds,'outerD2HSeconds',info.totalD2HSeconds, ...
        'outerGPUOperatorSeconds',info.totalGPUOperatorSeconds,'outerStorage','CPU');
    clear v0
end
