function one = run_method_B_fig1(sys,cfg,seed,budget)
%RUN_METHOD_B_FIG1 Nested reduced inverse Lanczos.
    [Aop,getStats]=fig1a_make_nested_krinv_instrumented(sys,cfg,cfg.nested.tolKr,cfg.nested.tolM, ...
        cfg.nested.maxitKr,cfg.nested.maxitM,budget);
    Iop=@(x)x; rng(seed,'twister');
    v0=to_gpu(randn(sys.nr,1)+1i*randn(sys.nr,1),cfg.gpu.precision);
    budget.checkCanContinue('Method B Lanczos start'); wait_for_gpu(v0); t=tic;
    [Y,theta,outerSteps,info]=Lanczos(Aop,Iop,Iop,sys.nr,cfg.spectrum.numEig, ...
        cfg.lanczos.tolerance,cfg.lanczos.maxRestartCycles,cfg.lanczos.krylovDimension, ...
        v0,true,cfg.lanczos.verboseInternal,false,1);
    wait_for_gpu(Y); wall=toc(t); budget.check('Method B Lanczos return');
    if ~info.converged, error('EXP1:NotConverged','Method B outer Lanczos did not converge: %d/%d.',info.numConverged,cfg.spectrum.numEig); end
    theta=real(theta(:)); if any(~isfinite(theta))||any(theta<=0), error('Method B invalid inverse Ritz values.'); end
    lambda=sort(1./theta,'ascend'); s=getStats();
    one=struct('lambda',lambda,'outerSteps',outerSteps,'inverseCalls',s.inverseCalls, ...
        'totalLinearSolverIterations',s.totalKrIterations+s.totalMassIterations, ...
        'primaryLinearIterations',s.totalKrIterations,'nestedLinearIterations',s.totalMassIterations, ...
        'dominantLinearSolveSeconds',s.totalMassSolveTime, ...
        'remainingInverseSeconds',max(s.totalInverseTime-s.totalMassSolveTime,0), ...
        'outerLanczosSeconds',max(wall-s.totalInverseTime,0),'totalWallSeconds',wall, ...
        'converged',true,'maxFinalRitzResidual',gather_scalar(max(info.ritzResiduals{end})), ...
        'maxLinearRelativeResidual',max(s.maxKrRelativeResidual,s.maxMassRelativeResidual), ...
        'averagePrimaryLinearIterations',s.averageKrIterations,'maxPrimaryLinearIterations',s.maxKrIterations, ...
        'averageNestedLinearIterations',s.averageMassIterations,'maxNestedLinearIterations',s.maxMassIterations);
    clear Y v0
end
