function plot_experiment2a_tradeoff(results,cfg,rootDir)
%PLOT_EXPERIMENT2A_TRADEOFF Final manuscript Figure 2(a).
% Accuracy--cost trade-off at N=5, n=40 for p=6,8,10 and
% 1^3,...,6^3 local Taylor centers.  This function is extracted from the
% tuned local Figure-2(a) plotting code; the obsolete workflow panel is not
% generated by this final combined package.

    if nargin < 3 || isempty(rootDir)
        rootDir = fileparts(mfilename('fullpath'));
    end
    figDir = fullfile(rootDir,'figures');
    if ~exist(figDir,'dir'), mkdir(figDir); end

    T = results.tradeoff;

    fontLabel      = 16;
    fontTick       = 14;
    fontLegend     = 14;
    fontAnnotation = 13;
    lineW      = 2.0;
    markerSize = 8.5;

    baseColors = get(groot,'defaultAxesColorOrder');
    if size(baseColors,1) < 3, baseColors = lines(3); end
    colors  = baseColors(1:3,:);
    markers = {'o','s','d'};

    pTrade = cfg.tradeoff.orders(:).';
    kTrade = cfg.tradeoff.blocksPerDimension(:).';
    nCenters = kTrade.^3;
    xPos = 1:numel(nCenters);

    rhoByCenter = zeros(size(nCenters));
    for j = 1:numel(nCenters)
        rr = T.RhoMax(T.NumCenters == nCenters(j));
        if isempty(rr), error('Missing radius for %d centers.', nCenters(j)); end
        if max(rr) - min(rr) > 1e-10 * max(1, max(abs(rr)))
            error('RhoMax unexpectedly depends on Taylor order.');
        end
        rhoByCenter(j) = rr(1);
    end

    f = new_manuscript_figure();
    mainAxPos = [0.12 0.29 0.73 0.63];
    ax = axes(f,'Position',mainAxPos);
    hold(ax,'on'); box(ax,'on'); grid(ax,'on');
    hErr = gobjects(numel(pTrade),1);

    yyaxis(ax,'left');
    set(ax,'YScale','log');
    for ip = 1:numel(pTrade)
        Ti = T(T.p == pTrade(ip),:);
        [~,ord] = sort(Ti.NumCenters); Ti = Ti(ord,:);
        [tf,xIdx] = ismember(Ti.NumCenters,nCenters);
        if ~all(tf), error('Unexpected center count in tradeoff table.'); end
        hErr(ip) = plot(ax,xIdx,Ti.RelativeFieldErrorMode10,['-' markers{ip}], ...
            'Color',colors(ip,:),'LineWidth',lineW,'MarkerSize',markerSize, ...
            'MarkerFaceColor',colors(ip,:),'MarkerEdgeColor',colors(ip,:));
    end
    ylabel(ax,'Relative field error $e_2$','Interpreter','latex','FontSize',fontLabel);
    local_log_ylim(ax,T.RelativeFieldErrorMode10);
    ax.YMinorGrid = 'on';

    yl = ylim(ax);
    for yref = [1e-8, 1e-10]
        if yref > yl(1) && yref < yl(2)
            plot(ax,[xPos(1) xPos(end)],[yref yref],':','Color',[0.55 0.55 0.55], ...
                'HandleVisibility','off');
        end
    end

    iadopt = find(pTrade == cfg.taylor.performanceOrder,1);
    xAdopt = find(nCenters == cfg.taylor.blocksPerDimension^3,1);
    if ~isempty(iadopt) && ~isempty(xAdopt)
        row = (T.p == pTrade(iadopt) & T.NumCenters == nCenters(xAdopt));
        yAdopt = T.RelativeFieldErrorMode10(find(row,1));
        plot(ax,xAdopt,yAdopt,'p','Color','k','MarkerSize',12,'LineWidth',1.3, ...
            'MarkerFaceColor','none','HandleVisibility','off');
        text(ax,xAdopt+0.15,yAdopt*1.35,'adopted','FontSize',fontAnnotation,'Interpreter','latex');
    end

    yyaxis(ax,'right');
    for ip = 1:numel(pTrade)
        Ti = T(T.p == pTrade(ip),:);
        [~,ord] = sort(Ti.NumCenters); Ti = Ti(ord,:);
        [~,xIdx] = ismember(Ti.NumCenters,nCenters);
        plot(ax,xIdx,Ti.GPUTimeSeconds,'--','Color',colors(ip,:),'LineWidth',1.6, ...
            'HandleVisibility','off');
        scatter(ax,xIdx,Ti.GPUTimeSeconds,56,'Marker',markers{ip}, ...
            'MarkerEdgeColor',colors(ip,:),'MarkerFaceColor','w','LineWidth',1.5, ...
            'HandleVisibility','off');
    end
    ylabel(ax,'GPU reconstruction time (s)','Interpreter','latex','FontSize',fontLabel);
    yt = T.GPUTimeSeconds; yt = yt(isfinite(yt) & yt >= 0);
    ymax = max(yt); if isempty(ymax) || ymax <= 0, ymax = 1; end
    ylim(ax,[0 1.16*ymax]);

    tickLabels = cell(size(nCenters));
    for j = 1:numel(nCenters)
        tickLabels{j} = sprintf('%d\\newline(%.2f)',nCenters(j),rhoByCenter(j));
    end
    set(ax,'FontSize',fontTick,'XTick',xPos,'XTickLabel',tickLabels, ...
        'TickLabelInterpreter','tex','LineWidth',1.05,'TickDir','out','XColor','k');
    ax.XTickLabelRotation = 0;
    xlim(ax,[0.75 numel(nCenters)+0.25]);
    ax.YAxis(1).Color = 'k'; ax.YAxis(2).Color = 'k';
    xlabel(ax,'Local centers / $r_{\mathrm{ph},\max}$','Interpreter','latex','FontSize',fontLabel);
    drawnow;
    xlab = ax.XLabel; xlab.Units = 'normalized'; xlab.Position(2) = -0.20;

    lgd = legend(ax,hErr,arrayfun(@(p)sprintf('$p=%d$',p),pTrade,'UniformOutput',false), ...
        'Interpreter','latex','FontSize',fontLegend,'Location','southwest');
    lgd.Box = 'on'; lgd.Units = 'normalized';
    lgd.Position = [0.15 0.35 0.19 0.18];

    draw_line_style_key(f,fontAnnotation);
    export_all(f,fullfile(figDir,cfg.output.figureTradeoffBase),cfg.output.pngResolution);
    close(f);
end

function f = new_manuscript_figure()
    f = figure('Color','w','Units','inches','Position',[1 1 5.60 4.35],'Renderer','painters');
    set(f,'PaperUnits','inches','PaperPosition',[0 0 5.60 4.35], ...
        'PaperSize',[5.60 4.35],'PaperPositionMode','manual');
end

function draw_line_style_key(fig,fontSize)
    boxPos = [0.39 0.77 0.30 0.095];
    annotation(fig,'rectangle',boxPos,'Color',[0.15 0.15 0.15], ...
        'LineWidth',0.9,'FaceColor','w');
    x1 = boxPos(1)+0.028; x2 = boxPos(1)+0.095; xt = boxPos(1)+0.120;
    ys = boxPos(2)+0.064; yd = boxPos(2)+0.028;
    annotation(fig,'line',[x1 x2],[ys ys],'Color',[0.12 0.12 0.12], ...
        'LineWidth',1.8,'LineStyle','-');
    annotation(fig,'line',[x1 x2],[yd yd],'Color',[0.12 0.12 0.12], ...
        'LineWidth',1.5,'LineStyle','--');
    annotation(fig,'textbox',[xt ys-0.015 0.20 0.025],'String','error', ...
        'Interpreter','latex','FontSize',fontSize,'LineStyle','none', ...
        'HorizontalAlignment','left','VerticalAlignment','middle','Margin',1);
    annotation(fig,'textbox',[xt yd-0.015 0.24 0.025],'String','GPU time', ...
        'Interpreter','latex','FontSize',fontSize,'LineStyle','none', ...
        'HorizontalAlignment','left','VerticalAlignment','middle','Margin',1);
end

function local_log_ylim(ax,y)
    y = double(y(:)); y = y(isfinite(y) & y > 0); if isempty(y), return; end
    lo = 10^floor(log10(min(y))); hi = 10^ceil(log10(max(y)));
    if lo == hi, lo = lo/10; hi = hi*10; end
    ylim(ax,[lo hi]);
end

function export_all(fig,base,res)
    drawnow; set(fig,'Renderer','painters');
    print(fig,[base '.eps'],'-depsc2','-painters');
    if exist('exportgraphics','file') == 2
        exportgraphics(fig,[base '.png'],'Resolution',res,'BackgroundColor','white');
    else
        print(fig,[base '.png'],'-dpng',sprintf('-r%d',res));
    end
    savefig(fig,[base '.fig']);
end
